name: Bug report
description: Report a bug with the HA Strava integration
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting bugs with the HA Strava integration. Bug reports should be detailed **with debug log messages and steps on reproducing the issue** to help developers determine what is going wrong.

        **If you are reporting a deprecation message from the log, please check that the message is for an HA deprecation (telling you to report the issue here), and that there is not already [a bug](https://github.com/craibo/ha_strava/issues?q=is%3Aissue+is%3Aopen+label%3Amaintenance) for the issue.** Most likely the deprecation is new in the latest HA release, and will not be "fixed" in the integration until late in the month or the next month, as fixes generally are not backwards compatible with older HA versions. Other deprecation messages can be aimed at you, the end user, to prompt you to update automations etc.

        If you are intending to create a pull request, an issue is not required, but please clearly describe the reason for your PR in the description of the PR.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of the bug you are experiencing.
    validations:
      required: true
  - type: textarea
    id: ha_version
    attributes:
      label: Home Assistant version
      description: |
        Home Assistant version
      placeholder: 2025.1.0
    validations:
      required: true
  - type: textarea
    id: strava_version
    attributes:
      label: HA Strava version
      description: |
        HA Strava version
      placeholder: 3.2.43
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        List any steps you need to take to reproduce this problem.
      placeholder: 1. Perform the ___ action...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable, please enable the integration debug logging, reproduce the issue and paste any relevant logs here.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, please include screenshots to illustrate the issue.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional information
      description: |
        Any other relevant information that might be helpful.
    validations:
      required: false
  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      description: |
        Please confirm the following
      options:
        - label: |
            I have confirmed that this bug has **not** already been reported.
          required: true
        - label: I am sure this is a bug, that is well enough described it can be investigated.
          required: true
        - label: |
            Log messages or diagnostics relevant to the issue are included.
          required: true
