set_activity_gear:
  name: Set Activity Gear
  description: Assign a shoe or bike to an activity by its Strava activity ID.
  fields:
    activity_id:
      required: true
      example: 1234567890
      selector:
        text:
    gear_id:
      required: true
      example: g23789926
      selector:
        text:
refresh_gear:
  name: Refresh Strava Gear
  description: Request an immediate refresh of Strava gear devices and sensors.
